spring.main.banner-mode=off
logging.level.root=ERROR

# Используем половину доступных процессоров
fractal.execution.processor-share=0.50

# 0 означает автоматический выбор
fractal.execution.thread-count=0

# Тяжёлые данные могут занимать до 80% свободной Java-кучи
fractal.render.available-heap-share=0.80
